global class Properties
{
    global final static String emptyString = '';
    global final static String newLineHTMLTag = '<br/>';
    global final static String NAProfilesPrefix = 'NA ';
    global final static String standardLeadConvertURL = '/lead/leadconvert.jsp?nooverride=1';
    global final static String isLeadBeingConverted = 'isLeadBeingConverted';
    global final static String leadId = 'leadId';
    global final static String trueString = 'true';
    global final static String retURL = 'retURL';
    global final static String utf8 = 'UTF-8';
    global final static String cannotFindAccountConfirmation = 'Are you sure you cannot find an existing Account and want to continue creating a new one?';
    global final static String cannotFindAccountConfirmationLeadConvert = 'Are you sure you cannot find an existing Account and want to continue converting the Lead?';
}